extension_dir = "C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=pdo_mysql
extension=openssl
extension=curl
extension=mbstring
extension=fileinfo
extension=gd
extension=mysqli

file_uploads = On
upload_max_filesize = 10M
post_max_size = 10M
memory_limit = 128M
